# Generated by Django 4.2.8 on 2024-01-11 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivatetokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivatetokens',
            name='Token',
        ),
        migrations.RemoveField(
            model_name='useractivatetokens',
            name='id',
        ),
        migrations.AlterField(
            model_name='useractivatetokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivatetokens',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
